php_factorial.lo: /home/raphael/code/php-module-c/php_factorial.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/raphael/code/php-module-c $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/raphael/code/php-module-c/php_factorial.c -o php_factorial.lo 
$(phplibdir)/php_factorial.la: ./php_factorial.la
	$(LIBTOOL) --mode=install cp ./php_factorial.la $(phplibdir)

./php_factorial.la: $(shared_objects_php_factorial) $(PHP_FACTORIAL_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS)  -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_php_factorial) $(PHP_FACTORIAL_SHARED_LIBADD)

